// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fcjEqjvkDDoj8fh9NrshcB
// Component: roq77CHjMSOm

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: fcjEqjvkDDoj8fh9NrshcB/projectcss
import sty from "./PlasmicCartCustomer.module.css"; // plasmic-import: roq77CHjMSOm/css

createPlasmicElementProxy;

export type PlasmicCartCustomer__VariantMembers = {};
export type PlasmicCartCustomer__VariantsArgs = {};
type VariantPropType = keyof PlasmicCartCustomer__VariantsArgs;
export const PlasmicCartCustomer__VariantProps = new Array<VariantPropType>();

export type PlasmicCartCustomer__ArgsType = {};
type ArgPropType = keyof PlasmicCartCustomer__ArgsType;
export const PlasmicCartCustomer__ArgProps = new Array<ArgPropType>();

export type PlasmicCartCustomer__OverridesType = {
  cartCustomer?: Flex__<"div">;
};

export interface DefaultCartCustomerProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCartCustomer__RenderFunc(props: {
  variants: PlasmicCartCustomer__VariantsArgs;
  args: PlasmicCartCustomer__ArgsType;
  overrides: PlasmicCartCustomer__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"cartCustomer"}
      data-plasmic-override={overrides.cartCustomer}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.cartCustomer
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  cartCustomer: ["cartCustomer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  cartCustomer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCartCustomer__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCartCustomer__VariantsArgs;
    args?: PlasmicCartCustomer__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCartCustomer__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCartCustomer__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCartCustomer__ArgProps,
          internalVariantPropNames: PlasmicCartCustomer__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCartCustomer__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "cartCustomer") {
    func.displayName = "PlasmicCartCustomer";
  } else {
    func.displayName = `PlasmicCartCustomer.${nodeName}`;
  }
  return func;
}

export const PlasmicCartCustomer = Object.assign(
  // Top-level PlasmicCartCustomer renders the root element
  makeNodeComponent("cartCustomer"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicCartCustomer
    internalVariantProps: PlasmicCartCustomer__VariantProps,
    internalArgProps: PlasmicCartCustomer__ArgProps
  }
);

export default PlasmicCartCustomer;
/* prettier-ignore-end */
