// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fcjEqjvkDDoj8fh9NrshcB
// Component: 5pz9O3Gb4dS6

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: fcjEqjvkDDoj8fh9NrshcB/projectcss
import sty from "./PlasmicShopBreadcrumbs.module.css"; // plasmic-import: 5pz9O3Gb4dS6/css

createPlasmicElementProxy;

export type PlasmicShopBreadcrumbs__VariantMembers = {};
export type PlasmicShopBreadcrumbs__VariantsArgs = {};
type VariantPropType = keyof PlasmicShopBreadcrumbs__VariantsArgs;
export const PlasmicShopBreadcrumbs__VariantProps =
  new Array<VariantPropType>();

export type PlasmicShopBreadcrumbs__ArgsType = {};
type ArgPropType = keyof PlasmicShopBreadcrumbs__ArgsType;
export const PlasmicShopBreadcrumbs__ArgProps = new Array<ArgPropType>();

export type PlasmicShopBreadcrumbs__OverridesType = {
  shopBreadcrumb?: Flex__<"div">;
};

export interface DefaultShopBreadcrumbsProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicShopBreadcrumbs__RenderFunc(props: {
  variants: PlasmicShopBreadcrumbs__VariantsArgs;
  args: PlasmicShopBreadcrumbs__ArgsType;
  overrides: PlasmicShopBreadcrumbs__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"shopBreadcrumb"}
      data-plasmic-override={overrides.shopBreadcrumb}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.shopBreadcrumb
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  shopBreadcrumb: ["shopBreadcrumb"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  shopBreadcrumb: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicShopBreadcrumbs__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicShopBreadcrumbs__VariantsArgs;
    args?: PlasmicShopBreadcrumbs__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicShopBreadcrumbs__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicShopBreadcrumbs__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicShopBreadcrumbs__ArgProps,
          internalVariantPropNames: PlasmicShopBreadcrumbs__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicShopBreadcrumbs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "shopBreadcrumb") {
    func.displayName = "PlasmicShopBreadcrumbs";
  } else {
    func.displayName = `PlasmicShopBreadcrumbs.${nodeName}`;
  }
  return func;
}

export const PlasmicShopBreadcrumbs = Object.assign(
  // Top-level PlasmicShopBreadcrumbs renders the root element
  makeNodeComponent("shopBreadcrumb"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicShopBreadcrumbs
    internalVariantProps: PlasmicShopBreadcrumbs__VariantProps,
    internalArgProps: PlasmicShopBreadcrumbs__ArgProps
  }
);

export default PlasmicShopBreadcrumbs;
/* prettier-ignore-end */
