// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fcjEqjvkDDoj8fh9NrshcB
// Component: GWHD6wfQu2Nw

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import ShopBreadcrumbs from "../../ShopBreadcrumbs"; // plasmic-import: 5pz9O3Gb4dS6/component
import ShopCatalog from "../../ShopCatalog"; // plasmic-import: hUE1dMxlmS4g/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: fcjEqjvkDDoj8fh9NrshcB/projectcss
import sty from "./PlasmicShopMain.module.css"; // plasmic-import: GWHD6wfQu2Nw/css

createPlasmicElementProxy;

export type PlasmicShopMain__VariantMembers = {};
export type PlasmicShopMain__VariantsArgs = {};
type VariantPropType = keyof PlasmicShopMain__VariantsArgs;
export const PlasmicShopMain__VariantProps = new Array<VariantPropType>();

export type PlasmicShopMain__ArgsType = {};
type ArgPropType = keyof PlasmicShopMain__ArgsType;
export const PlasmicShopMain__ArgProps = new Array<ArgPropType>();

export type PlasmicShopMain__OverridesType = {
  shopMain?: Flex__<"div">;
  shopBreadcrumbs?: Flex__<typeof ShopBreadcrumbs>;
  shopCatalog?: Flex__<typeof ShopCatalog>;
};

export interface DefaultShopMainProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicShopMain__RenderFunc(props: {
  variants: PlasmicShopMain__VariantsArgs;
  args: PlasmicShopMain__ArgsType;
  overrides: PlasmicShopMain__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"shopMain"}
      data-plasmic-override={overrides.shopMain}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.shopMain
      )}
    >
      <ShopBreadcrumbs
        data-plasmic-name={"shopBreadcrumbs"}
        data-plasmic-override={overrides.shopBreadcrumbs}
        className={classNames("__wab_instance", sty.shopBreadcrumbs)}
      />

      <ShopCatalog
        data-plasmic-name={"shopCatalog"}
        data-plasmic-override={overrides.shopCatalog}
        className={classNames("__wab_instance", sty.shopCatalog)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  shopMain: ["shopMain", "shopBreadcrumbs", "shopCatalog"],
  shopBreadcrumbs: ["shopBreadcrumbs"],
  shopCatalog: ["shopCatalog"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  shopMain: "div";
  shopBreadcrumbs: typeof ShopBreadcrumbs;
  shopCatalog: typeof ShopCatalog;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicShopMain__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicShopMain__VariantsArgs;
    args?: PlasmicShopMain__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicShopMain__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicShopMain__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicShopMain__ArgProps,
          internalVariantPropNames: PlasmicShopMain__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicShopMain__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "shopMain") {
    func.displayName = "PlasmicShopMain";
  } else {
    func.displayName = `PlasmicShopMain.${nodeName}`;
  }
  return func;
}

export const PlasmicShopMain = Object.assign(
  // Top-level PlasmicShopMain renders the root element
  makeNodeComponent("shopMain"),
  {
    // Helper components rendering sub-elements
    shopBreadcrumbs: makeNodeComponent("shopBreadcrumbs"),
    shopCatalog: makeNodeComponent("shopCatalog"),

    // Metadata about props expected for PlasmicShopMain
    internalVariantProps: PlasmicShopMain__VariantProps,
    internalArgProps: PlasmicShopMain__ArgProps
  }
);

export default PlasmicShopMain;
/* prettier-ignore-end */
