export interface DraftOrdersList {
    limit: number;
    offset: number;
    count: number;
    draft_orders: {
        id: string;
        version: number;
        region_id: string;
        customer_id: string;
        sales_channel_id: string;
        email: string;
        currency_code: string;
        items: {
            id: string;
            title: string;
            subtitle: string;
            thumbnail: string;
            variant_id: string;
            product_id: string;
            product_title: string;
            product_description: string;
            product_subtitle: string;
            product_type: string;
            product_collection: string;
            product_handle: string;
            variant_sku: string;
            variant_barcode: string;
            variant_title: string;
            variant_option_values: {
                [key: string]: string;
            };
            requires_shipping: boolean;
            is_discountable: boolean;
            is_tax_inclusive: boolean;
            unit_price: number;
            quantity: number;
            detail: Record<string, unknown>;
            created_at: string;
            updated_at: string;
            metadata: Record<string, unknown>;
            original_total: number;
            original_subtotal: number;
            original_tax_total: number;
            item_total: number;
            item_subtotal: number;
            item_tax_total: number;
            total: number;
            subtotal: number;
            tax_total: number;
            discount_total: number;
            discount_tax_total: number;
            refundable_total: number;
            refundable_total_per_unit: number;
            product_type_id: string;
        }[];
        shipping_methods: {
            id: string;
            order_id: string;
            name: string;
            amount: number;
            is_tax_inclusive: boolean;
            shipping_option_id: string;
            data: Record<string, unknown>;
            metadata: Record<string, unknown>;
            original_total: number;
            original_subtotal: number;
            original_tax_total: number;
            total: number;
            subtotal: number;
            tax_total: number;
            discount_total: number;
            discount_tax_total: number;
            created_at: string;
            updated_at: string;
        }[];
        payment_status: "canceled" | "completed" | "pending";
        fulfillment_status: "canceled" | "fulfilled" | "pending";
        summary: {
            total: number;
            subtotal: number;
            total_tax: number;
            ordered_total: number;
            fulfilled_total: number;
            returned_total: number;
            return_request_total: number;
            write_off_total: number;
            paid_total: number;
            refunded_total: number;
        };
        created_at: string;
        updated_at: string;
        original_item_total: number;
        original_item_subtotal: number;
        original_item_tax_total: number;
        item_total: number;
        item_subtotal: number;
        item_tax_total: number;
        original_total: number;
        original_subtotal: number;
        original_tax_total: number;
        total: number;
        subtotal: number;
        tax_total: number;
        discount_total: number;
        discount_tax_total: number;
        gift_card_total: number;
        gift_card_tax_total: number;
        shipping_total: number;
        shipping_subtotal: number;
        shipping_tax_total: number;
        original_shipping_total: number;
        original_shipping_subtotal: number;
        original_shipping_tax_total: number;
        status: string;
    };
}
