/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BlogPostImport } from './routes/blog-post'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as StoreIndexImport } from './routes/store/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as StoreStoreImport } from './routes/store/store'
import { Route as StoreProductsImport } from './routes/store/products'
import { Route as StoreOrdersIndexImport } from './routes/store/orders/index'

// Create/Update Routes

const BlogPostRoute = BlogPostImport.update({
  id: '/blog-post',
  path: '/blog-post',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StoreIndexRoute = StoreIndexImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const StoreStoreRoute = StoreStoreImport.update({
  id: '/store/store',
  path: '/store/store',
  getParentRoute: () => rootRoute,
} as any)

const StoreProductsRoute = StoreProductsImport.update({
  id: '/store/products',
  path: '/store/products',
  getParentRoute: () => rootRoute,
} as any)

const StoreOrdersIndexRoute = StoreOrdersIndexImport.update({
  id: '/store/orders/',
  path: '/store/orders/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/blog-post': {
      id: '/blog-post'
      path: '/blog-post'
      fullPath: '/blog-post'
      preLoaderRoute: typeof BlogPostImport
      parentRoute: typeof rootRoute
    }
    '/store/products': {
      id: '/store/products'
      path: '/store/products'
      fullPath: '/store/products'
      preLoaderRoute: typeof StoreProductsImport
      parentRoute: typeof rootRoute
    }
    '/store/store': {
      id: '/store/store'
      path: '/store/store'
      fullPath: '/store/store'
      preLoaderRoute: typeof StoreStoreImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreIndexImport
      parentRoute: typeof rootRoute
    }
    '/store/orders/': {
      id: '/store/orders/'
      path: '/store/orders'
      fullPath: '/store/orders'
      preLoaderRoute: typeof StoreOrdersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog-post': typeof BlogPostRoute
  '/store/products': typeof StoreProductsRoute
  '/store/store': typeof StoreStoreRoute
  '/login': typeof LoginIndexRoute
  '/store': typeof StoreIndexRoute
  '/store/orders': typeof StoreOrdersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog-post': typeof BlogPostRoute
  '/store/products': typeof StoreProductsRoute
  '/store/store': typeof StoreStoreRoute
  '/login': typeof LoginIndexRoute
  '/store': typeof StoreIndexRoute
  '/store/orders': typeof StoreOrdersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog-post': typeof BlogPostRoute
  '/store/products': typeof StoreProductsRoute
  '/store/store': typeof StoreStoreRoute
  '/login/': typeof LoginIndexRoute
  '/store/': typeof StoreIndexRoute
  '/store/orders/': typeof StoreOrdersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog-post'
    | '/store/products'
    | '/store/store'
    | '/login'
    | '/store'
    | '/store/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog-post'
    | '/store/products'
    | '/store/store'
    | '/login'
    | '/store'
    | '/store/orders'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog-post'
    | '/store/products'
    | '/store/store'
    | '/login/'
    | '/store/'
    | '/store/orders/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogPostRoute: typeof BlogPostRoute
  StoreProductsRoute: typeof StoreProductsRoute
  StoreStoreRoute: typeof StoreStoreRoute
  LoginIndexRoute: typeof LoginIndexRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreOrdersIndexRoute: typeof StoreOrdersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogPostRoute: BlogPostRoute,
  StoreProductsRoute: StoreProductsRoute,
  StoreStoreRoute: StoreStoreRoute,
  LoginIndexRoute: LoginIndexRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreOrdersIndexRoute: StoreOrdersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/blog-post",
        "/store/products",
        "/store/store",
        "/login/",
        "/store/",
        "/store/orders/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/blog-post": {
      "filePath": "blog-post.tsx"
    },
    "/store/products": {
      "filePath": "store/products.tsx"
    },
    "/store/store": {
      "filePath": "store/store.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/store/": {
      "filePath": "store/index.tsx"
    },
    "/store/orders/": {
      "filePath": "store/orders/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
