/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BlogPostImport } from './routes/blog-post'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AuthenticatedStoreImport } from './routes/_authenticated/store'
import { Route as AuthenticatedCatalogImport } from './routes/_authenticated/catalog'

// Create/Update Routes

const BlogPostRoute = BlogPostImport.update({
  id: '/blog-post',
  path: '/blog-post',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedStoreRoute = AuthenticatedStoreImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCatalogRoute = AuthenticatedCatalogImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/blog-post': {
      id: '/blog-post'
      path: '/blog-post'
      fullPath: '/blog-post'
      preLoaderRoute: typeof BlogPostImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreImport
      parentRoute: typeof AuthenticatedImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/blog-post': typeof BlogPostRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/store': typeof AuthenticatedStoreRoute
  '/login': typeof LoginIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/blog-post': typeof BlogPostRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/store': typeof AuthenticatedStoreRoute
  '/login': typeof LoginIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/blog-post': typeof BlogPostRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/login/': typeof LoginIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/blog-post'
    | '/catalog'
    | '/store'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/about' | '/blog-post' | '/catalog' | '/store' | '/login'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/blog-post'
    | '/_authenticated/catalog'
    | '/_authenticated/store'
    | '/login/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogPostRoute: typeof BlogPostRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogPostRoute: BlogPostRoute,
  LoginIndexRoute: LoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/about",
        "/blog-post",
        "/login/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/catalog",
        "/_authenticated/store"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/blog-post": {
      "filePath": "blog-post.tsx"
    },
    "/_authenticated/catalog": {
      "filePath": "_authenticated/catalog.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/store": {
      "filePath": "_authenticated/store.tsx",
      "parent": "/_authenticated"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
